name=MotusDrivers
version=0.1.0
author=Guilherme Melo
maintainer=guilhermeanglopp
sentence=Description for sentence
paragraph=Description for paragraph
category=drivers
architectures=esp32
includes=MotusDrivers.h