; Passo 9 — ESP32 com Task dedicada no Core 1
; pio run -d lib/MotusDrivers/examples/04_esp32_task

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../../../

